def includeme(config):
    config.include('.catalog')
    config.include('.cluster_tags')
    config.include('.i18n')
    config.include('.organisation')
    config.include('.question')
    config.include('.question_type')
    config.include('.question_types')
    config.include('.question_widgets')
    config.include('.questions')
    config.include('.survey')
    config.include('.survey_section')
    config.include('.text_section')
    config.include('.workflows')
